# Generated by Django 4.2.3 on 2023-07-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to='post_image/%Y/%m/%d'),
        ),
    ]
